name: seizethedaycoffee
favicon: null
layout_spectrum: 0.35701
typography_spectrum: 0.2220977998804301
title: Seize the day Coffee Roaster
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040205'
    - '#ceb1a7'
    - '#482514'
    - '#6e432b'
    - '#9d7364'
  brandStrength: 0.4951818024273962
  lightness: 0.4535873008426279
  saturation: 0.45591417513787746
  rhythmicContrast: 0.8255426455289125
purpose: []
